image: node:12.6.0

cache:
  paths:
    - node_modules/

stages:
  - setup
  - lint
  - test

setup:
  stage: setup
  script: yarn

lint:
  stage: lint
  script: yarn lint

test:
  stage: test
  script: yarn test
